#ifndef MAIN_H
#define MAIN_H

//PROGRAMME: 247-527Atelier3a
//DESCRIPTION: programme qui sert de base pour l'introduction au HTML, Javascript, etc

//HISTORIQUE:
// 2022-04-11, Yves Roy: création

//inclusions globales

//DEFINITIONS REQUISES PAR LE MODULE:
//Dependances materielles:
#define RXD2 16
#define TXD2 17
#define PILOTEENTREE1_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREE1_BROCHE 21
#define PILOTEIOT1_BROCHE 13
#define PILOTEIOT1_ETAT_INITIAL_A_ZERO
#define PILOTEANALOGUE0_BROCHE A2
#define PILOTEANALOGUE1_BROCHE A3
#define PILOTEI2C1_FREQUENCE_D_HORLOGE_EN_HZ 400000
#define INTERFACEENTREE1_VALEUR_LUE_SI_ACTIVE  0   
#define INTERFACEENTREE1_VALEUR_LUE_SI_INACTIVE 1
#define INTERFACEENTREE1_FREQUENCE_DES_LECTURES_EN_HZ  125
#define INTERFACEENTREE1_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION 10
#define INTERFACET1_VALEUR_POUR_ALLUMER  1   
#define INTERFACET1_VALEUR_POUR_ETEINDRE 0

//Dependances logicielles:
#define SERVICETASKSERVER_PERIODE_EN_US (4000L)
#define SERVICEBASEDETEMPS_FREQUENCE_EN_HZ ((1000000L)/SERVICETASKSERVER_PERIODE_EN_US)
#define PROCESSUSCLIGNOTANT_TEMPS_ALLUME_EN_MS 500
#define PROCESSUSCLIGNOTANT_TEMPS_ETEINT_EN_MS 500
#define PROCESSUSMOTEURPASAPAS_TEMPS_PAR_COMMANDE_EN_MS 8

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES 3
#define INTERFACEENTREE1_PHASE 0
#define PROCESSUSMOTEURPASAPAS_PHASE 1
#define PROCESSUSCLIGNOTANT_PHASE 2


#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES_DANS_LOOP 1

//INFORMATION PUBLIQUE:
//Definitions publiques:
//pas de definitions publiques

//Variables publiques:
//pas de variables publiques

//Fonctions publiques:
//pas de fonctions publiques

#endif
